services:
  api:
    build: .
    container_name: autonomikit_api
    env_file: .env
    ports:
      - "8000:8000"
  web:
    build: ./dashboard
    container_name: autonomikit_web
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    ports:
      - "3000:3000"
